### ISSUE TITLE
Tab key causing uncaught error

### ISSUE THREAD

**Issue by peter-chow** [mkhstar/suneditor-react#172]
Hi,

I'm experiencing an issue where pressing the tab key in the editor doesn't insert a tab but instead causes an uncaught error:

Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.getByteLength (main.js:947)
    at Object.getCharLength (main.js:2206)
    at Object.checkCharCount (main.js:2200)
    at Object.insertNode (main.js:1921)
    at HTMLDivElement.onKeyDown_wysiwyg (main.js:2308)

I have a single instance of the editor (version 2.15.2) on a page.

I can disable tabs using the tabDisable option which eliminates the error, but I would like to allow tabs in the text.  Also, it looks like the tabDisable option is currently defined as a string instead of a boolean.

**Comment by mkhstar** [comment]
Hi @peter-chow 
This will be fixed in the next version. I will inform you when it is released

**Comment by mkhstar** [comment]
Hi @peter-chow 
fixed in version 2.16.0

**Comment by peter-chow** [comment]
Thanks @mkhstar.  Unfortunately, I’ve tested version 2.16.0, and it still appears to throw an unhandled exception.  The call stack is still the same (but the positions are slightly different).

Regards,
Peter

**Comment by peter-chow** [comment]
Thanks @mkhstar.  Unfortunately, I’ve tested version 2.16.0, and it still appears to throw an unhandled exception.  The call stack is still the same (but the positions are slightly different).

Regards,
Peter

**Comment by peter-chow** [comment]
Hi @mkhstar.  Sundeditor has been updated to version 2.37.0 to resolve the unhandled error when pressing the tab key.  Can you please update to use this version to resolve the problem.
