### ISSUE TITLE
onImageUploadBefore does not work fine

### ISSUE THREAD

**Issue by dacoten** [mkhstar/suneditor-react#310]
@mkhstar 
Hi @mkhstar, I am using the function **onImageUploadBefore** to upload the image to the server. But it did not work as excepted.

I got the error below:
```
uploadHandler is not a function
```
## Version
Next version: 13.3.0, react: 18.2.0, suneditor: 2.44.12, suneditor-react: 3.5.0

Here is my code:
```ts
const RichEditor = memo<Props>(function RichEditor({
  height = '300',
  value,
  setValue,
}) {
  const handleImageUploadBefore = useCallback(
    (files: Array<File>, info: object, uploadHandler: UploadBeforeHandler) => {
      // Do not use async function
      try {
        const file = files[0];
        const formData = new FormData();
        formData.append('files', file);

        axiosClient
          .post('/uploads', formData, {
            headers: {
              'Content-Type': 'multipart/form-data',
            },
          })
          .then((res) => res.data)
          .then((images) => {
            const handleData = {
              result: [
                {
                  url: getURLImage(images[0].path),
                  name: images[0].originalName,
                  size: images[0].size,
                },
              ],
            };

            return uploadHandler(handleData);
          });
      } catch (error) {
        // eslint-disable-next-line no-console
        console.log(error);
        return false;
      }
    },
    [],
  );

  return (
    <SunEditor
      height={height}
      setOptions={{
        buttonList: [
          ['undo', 'redo'],
          [
            'fontSize',
            'formatBlock',
            'paragraphStyle',
            'blockquote',
            'bold',
            'underline',
            'italic',
            'fontColor',
            'textStyle',
            'removeFormat',
            'outdent',
            'indent',
            'align',
            'horizontalRule',
            'list',
            'lineHeight',
            'table',
          ],
          ['link', 'image', 'video', 'audio'],
          ['fullScreen'],
        ],
      }}
      onImageUploadBefore={handleImageUploadBefore}
      setContents={value}
      onChange={setValue}
    />
  );
});
```

**Comment by 3ALabs** [comment]
`editor.onImageUploadBefore: function (files, info, core, uploadHandler) {
    return Boolean || return (new FileList) || return undefined;
}
`
When I looked at the document in sunEditor, it was written differently.
It worked when you specified uploadHandler as the fourth parameter.

**Comment by pluto21** [comment]
`editor.onImageUploadBefore: function (files, info, core, uploadHandler) {
    return Boolean || return (new FileList) || return undefined;
}
`

When I looked at the document in sunEditor, it was written differently.
I added a 'core' and it's fine.

**Comment by UnikoveNeeraj** [comment]
In version 3.5.0 image upload is not working. Giving error
image.js:383 Uncaught Error: [SUNEDITOR.image.submit.fail] cause : "uploadHandler is not a function"
    at Object.submit (image.js:383:1)

**Comment by mkhstar** [comment]
Thanks for opening the issue. The latest version 3.6.1 should resolve the issue. The order of the params were causing the issue

**Comment by ricardopacheco** [comment]
@mkhstar Problem persist!

**Comment by harshitrastogi992** [comment]
This is still not fixed

 "suneditor": "^2.45.1",
 "suneditor-react": "^3.6.1",
