### ISSUE TITLE
TypeError Cannot read property 'style' of null

### ISSUE THREAD

**Issue by doug-luce-kubra** [mkhstar/suneditor-react#53]
Hello, thanks for your work with with this it's appreciated.

Currently, I'm using sun editor to persist images in base64 to a database, but they are getting wrapped in a div with a class name of `se-component` which is causing an error `TypeError Cannot read property 'style' of null`.  I've replicated it in this code sandbox [https://codesandbox.io/s/setoptions-failed-with-cannot-read-property-style-of-null-4j8w6?file=/src/App.js](https://codesandbox.io/s/setoptions-failed-with-cannot-read-property-style-of-null-4j8w6?file=/src/App.js) By removing the `se-compoent` class it works just fine. 

I'm not sure what I'm missing, is it intended that the `<img` tag is wrapped in a div with this class?

Thanks,

Doug

**Comment by mkhstar** [comment]
Hi @doug-luce-kubra 
Thanks for notifying us with this error. I think it is a bug in the core suneditor library. @JiHong88 can we do something about it? I have included the stack trace below.
![Screen Shot 2020-05-13 at 6 46 46 PM](https://user-images.githubusercontent.com/26695391/81834869-3bb41e80-954a-11ea-9c28-47a525ea1cae.png)

**Comment by doug-luce-kubra** [comment]
@mkhstart @JiHong88 If it's preferred I can open an issue on the main repository.

**Comment by JiHong88** [comment]
Hi, @doug-luce-kubra 
Yes, please open this issue in main repository.

**Comment by mkhstar** [comment]
@doug-luce-kubra you can open an issue at the main repository. Thanks for notifying us

**Comment by doug-luce-kubra** [comment]
@mkhstar The issue has been fixed in the main repository, do you have an estimate of when the react component will be updated to use the latest version?
I appreciate your efforts on this and thank you.

**Comment by changyeamoon** [comment]
@mkhstar I believe this issue is still happening in the latest release 3.3.0.

Can you confirm @doug-luce-kubra ?
